### ISSUE TITLE
Auth Config not found 

### ISSUE THREAD

**Issue by arwwwind** [jwill9999/recipe-app#3]
import { config } from '../../../.configuration';

at least a demo one will do

**Comment by komalg1** [comment]
Facing the same issue. configuration module not found

**Comment by jwill9999** [comment]
Sorry for the late response I didn’t realise you’d commented. I will add a public configuration file this week and update you accordingly

**Comment by jwill9999** [comment]
Please see readme for details on configuration file and example code. The config file only includes the firebase generated keys generated to access your firebase auth service which you will need to create yourself. This is free.
